### ISSUE TITLE
Sorry for this. I have no idea how to reach you

### ISSUE THREAD

**Issue by Aninuscsalas** [Vidanox/vidanox.github.io#1]
Just Wanted to get in contact with you. Please release [Wynncraft Enchanted](https://modrinth.com/modpack/wynncraft-enhanced) source code, so I'm able to report issues for it. I have found some bugs.

**Comment by Vidanox** [comment]
Hi! I'm rather new to this stuff, but here you go:
https://github.com/Vidanox/WynncraftEnhanced
Would you mind telling me what specific bug have you come across?
